## Практическая работа

В этой практической работе четыре обязательные задачи.

*Обязательные задачи* нужно сделать для того, чтобы проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении моделей деревьев решений.
2.   Потренироваться в обучении моделей случайного леса. 
3.   Научиться оценивать качество моделей с помошью Accuracy и confusion matrix.
4.   Научиться увеличивать качество моделей с помощью тюнинга параметров.

Что оценивается:

*   Все пункты и критерия приёмки задания выполнены.
*   Удаление колонок по результатам feature_importance и определения типов производится с помощью кода, а не перечислением их вручную.

## Обязательные задачи

### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

0. *Подготовка базовой модели*

Обучите простую модель классификации с помощью DecisionTreeClassifier на данных из датасета vehicles_dataset_prepared.csv. Для этого сделайте следующие шаги:

1. Обучите модель дерева решений с зафиксированным random_state на тренировочной выборке.
2. Сделайте предикт на тестовой выборке.
3. Замерьте точность на тестовой выборке и выведите матрицу ошибок. 
4. Удалите фичи с нулевыми весами по feature_importance из тренировочной и тестовой выборок.
5. Заново обучите модель и измерьте качество.

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
df = pd.read_csv('vehicles_dataset_prepared.csv')

df_prepared = df.copy()
df_prepared = df_prepared.drop(['price', 'odometer/price_std'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [5]:
# Ваш код здесь 
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
predicted_test=clf.predict(x_test)
predicted_train=clf.predict(x_train)
print(accuracy_score(y_train,predicted_train))
print(accuracy_score(y_test,predicted_test))

1.0
0.6718641718641719

In [6]:
clf.feature_importances_

array([0.0322824 , 0.00041354, 0.00212334, ..., 0.00141112, 0.01639904,
       0.01820434])

In [7]:
f_im_list = list(zip(x_train.columns,clf.feature_importances_))
f_im_list.sort(key=lambda x:x[1],reverse=True)
len(f_im_list)

1460

In [8]:
for i in range(len(f_im_list)):
    if f_im_list[i][1]==0:
        df_prepared=df_prepared.drop(f_im_list[i][0],axis=1)
df_prepared

,id,price_category,is_audi,is_ford,is_chevrolet,is_toyota,x0_diesel,x0_electric,x0_gas,x0_hybrid,...,lat_std,long_std,year_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std,month_std,dayofweek_std,diff_years_std
0,7308295377,high,0,0,0,0,1.0,0.0,0.0,0.0,...,-0.619172,0.484245,1.322394,0.632075,-0.155788,1.163032,1.910669,-0.615846,1.120284,-1.322394
1,7316380095,medium,0,1,0,0,0.0,0.0,0.0,0.0,...,0.388014,1.110800,0.695973,-0.646781,-0.155788,0.932087,1.235799,1.623784,-1.374972,-0.695973
2,7313733749,high,0,0,0,0,0.0,0.0,1.0,0.0,...,-0.843059,0.531185,0.852578,0.560744,-0.155788,0.470197,0.560930,-0.615846,-0.376870,-0.852578
3,7308210929,medium,0,0,0,1,0.0,0.0,1.0,0.0,...,-0.504509,0.853562,0.226157,0.180435,-0.155788,-0.915473,-0.788810,-0.615846,1.120284,-0.226157
4,7303797340,medium,0,0,0,0,0.0,0.0,0.0,0.0,...,-0.460101,0.557607,0.069552,0.766366,-0.155788,1.163032,1.910669,-0.615846,0.122182,-0.069552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9614,7304876387,low,0,0,0,1,0.0,0.0,1.0,0.0,...,0.615626,0.823646,-1.496501,-0.376744,-0.155788,-0.915473,-0.788810,-0.615846,1.120284,1.496501
9615,7316152972,medium,0,0,0,0,0.0,0.0,1.0,0.0,...,0.806702,0.903947,-0.556869,-0.654060,-0.155788,-0.453583,-0.788810,1.623784,-1.374972,0.556869
9616,7310993818,low,1,0,0,0,0.0,0.0,1.0,0.0,...,1.105428,-1.628875,-0.087054,-0.668253,-0.155788,1.509450,1.910669,-0.615846,0.122182,0.087054
9617,7306637427,high,0,0,0,0,0.0,0.0,0.0,1.0,...,0.773939,0.251959,0.539367,0.327100,-0.155788,-0.569055,-0.788810,-0.615846,-0.376870,-0.539367
9618,7311960763,high,0,0,0,0,0.0,0.0,1.0,0.0,...,-0.337738,0.985465,0.852578,0.632439,-0.155788,1.163032,1.910669,-0.615846,1.120284,-0.852578

In [9]:


x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [10]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
predicted_test=clf.predict(x_test)
predicted_train=clf.predict(x_train)
print(accuracy_score(y_train,predicted_train))
print(accuracy_score(y_test,predicted_test))

1.0
0.6729036729036729

1. *Подготовка модели случайного леса*

Обучите простую модель классификации с помощью RandomForestClassifier. Для этого сделайте следующие шаги:
1. На новых урезанных семплах тренировочной и тестовой выборок обучите модель случайного леса с зафиксированным random_state=50. 

2. Сделайте предикт и посчитайте точность модели и матрицу ошибок. Сравните с предыдущей моделью дерева решений. Есть ли случаи, когда модель из пункта 1 отрабатывает лучше, чем модель случайного леса?

In [11]:
# Ваш код здесь 
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=50)
rt_clf = RandomForestClassifier()
rt_clf.fit(x_train, y_train)

predicted_train_rt = rt_clf.predict(x_train)
predicted_test_rt = rt_clf.predict(x_test)

print(accuracy_score(y_train, predicted_train_rt))
print(accuracy_score(y_test, predicted_test_rt))

1.0
0.7571032571032571

2. *Тюнинг модели случайного леса*

Увеличьте точность модели на тестовом датасете RandomForestClassifier c помощью тюнинга параметров. 

Параметры, которые можно настраивать для увеличения точности:

```
    `bootstrap'
    'max_depth'
    'max_features'
    'min_samples_leaf'
    'min_samples_split'
    'random_state'
    'n_estimators'

```



С описанием каждого из параметров можно ознакомиться в документации:


https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

Задание засчитывается, если значение метрики строго выше 0,76 на тестовом датасете.

In [16]:
# Ваш код здесь 
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=50)
rt_clf = RandomForestClassifier(max_features='log2',n_estimators=300, max_depth=100,min_samples_split=5,random_state=42)
rt_clf.fit(x_train, y_train)

predicted_train_rt = rt_clf.predict(x_train)
predicted_test_rt = rt_clf.predict(x_test)

print(accuracy_score(y_train, predicted_train_rt))
print(accuracy_score(y_test, predicted_test_rt))

0.9940591118372196
0.7616077616077616

3. *Анализ влияния фичей на модель*

Во всех задачах до вы работали над подготовленным датасетом, где фичи были заранее извлечены из текстовых переменных, отскейлены и пропущены через One Hot Encoder. Сравним, какой была бы предсказательная способность модели, если бы мы использовали только сырые данные из исходного датасета. Для этого проделайте следующие шаги:

1. Загрузите датасет `vehicles_dataset_old.csv`.
2. Удалите из него переменную `price` и все строковые колонки. Дерево решений и случайный лес не умеют самостоятельно работать со строковыми значениями.
3. Сформируйте x_train и x_test так же, как они были сформированы в предыдущих заданиях.
4. Обучите свою лучшую модель случайного леса на новых данных и замерьте качество. Убедитесь, что оно ухудшилось.
5. Найдите три фичи, которые лучшим образом повлияли на предсказательную способность модели.

In [23]:
df_old = pd.read_csv('vehicles_dataset_old.csv')
df_old.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,clean,other,https://images.craigslist.org/00F0F_5UAXmOzC18...,Carvana is the safer way to buy a car During t...,tn,35.970000,-83.940000,2021-04-08T15:10:56-0400,medium,2021-04-08 19:10:56+00:00

In [24]:
# Ваш код здесь 
df_old=df_old.drop(['price'],axis=1)

In [25]:
df_old.columns

Index(['id', 'url', 'region', 'region_url', 'year', 'manufacturer', 'model',
       'fuel', 'odometer', 'title_status', 'transmission', 'image_url',
       'description', 'state', 'lat', 'long', 'posting_date', 'price_category',
       'date'],
      dtype='object')

In [28]:
df_old=df_old[['year','odometer','lat','long','price_category']]
df_old

      year  odometer        lat        long price_category
0     2020     27442  35.060000  -85.250000           high
1     2016     60023  40.821805  -74.061962         medium
2     2017     14048  33.779214  -84.411811           high
3     2013    117291  35.715954  -78.655304         medium
4     2012     80465  35.970000  -83.940000         medium
...    ...       ...        ...         ...            ...
9614  2002    150000  42.123900  -79.189500            low
9615  2008    113573  43.216990  -77.755610         medium
9616  2011    150184  44.925908 -122.982753            low
9617  2015     61943  43.029559  -89.397796           high
9618  2017     35921  36.670000  -76.300000           high

[9619 rows x 5 columns]

In [30]:
x = df_old.drop(['price_category'],axis=1)
y = df_old['price_category']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=50)
rt_clf2 = RandomForestClassifier()
rt_clf2.fit(x_train, y_train)

predicted_train_rt2 = rt_clf2.predict(x_train)
predicted_test_rt2 = rt_clf2.predict(x_test)

print(accuracy_score(y_train, predicted_train_rt2))
print(accuracy_score(y_test, predicted_test_rt2))

0.999702955591861
0.6254331254331255

In [33]:
f_im_list2 = list(zip(x_train.columns,rt_clf2.feature_importances_))
f_im_list2.sort(key=lambda x:x[1],reverse=True)
f_im_list2

[('odometer', 0.3314338082374749),
 ('year', 0.2379324425649645),
 ('long', 0.21569944153900106),
 ('lat', 0.21493430765855956)]

In [ ]:
('odometer', 0.3314338082374749),
 ('year', 0.2379324425649645),
 ('long', 0.21569944153900106)